import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as React from "react";
import { render } from "react-dom";
import { animated, useSpring } from "react-spring";
import { useScroll } from "react-use-gesture";
import { useState } from 'react';
import { Dropdown } from 'semantic-ui-react'
import Merchants from './merchants.json'
import Link from 'next/link';

export default function Redeem() {

    const [token, setToken] = useState('Select a Card')
    const [tokenBalance, setTokenBalance] = useState(0)

    function handleChange(value) {
      console.log(token)
      console.log(value)
      setToken(value);
    }

    async function addBalance() {
      let RandomNumber = Math.floor(Math.random() * 100) + 1;
      const curBalance = tokenBalance + RandomNumber
      setTokenBalance(curBalance);
    }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Redeem</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <div className='header'>
        <h4 style={{'display': 'flex', 'justifyContent': 'center', 'marginBottom': '3rem'}}>
          Token Balance: {tokenBalance}
        </h4>
      </div>
        <h1 className={styles.title} onClick={()=> addBalance()} style={{'marginBottom': '4rem'}}>
          <a>Redeem</a>
        </h1>
        <div className='dropDown'>
          <Dropdown
              text={token}
              style={{'paddingRight': '3em !important', 'width': '190px'}}
              floating
              labeled
              button
              className='icon'
            >
              <Dropdown.Menu>
                <Dropdown.Header/>
                {Merchants.Merchant.map((option) => (
                  <Dropdown.Item text={option.value} {...option} onClick={() => handleChange(option.value)}/>
                ))}
              </Dropdown.Menu>
            </Dropdown>
          </div>
          <input type="" pattern="^-?[0-9]\d*\.?\d*$" placeholder="Enter your card number" style={{'marginTop': '30px'}} id="first" name="first" />
          <h3 style={{'position': 'relative', 'marginTop': '400px'}}>
          <Link
              href={{
                pathname: "/swap",
                query: tokenBalance, // the data
              }}
           >
            <a style={{'color': 'black'}}>Ready to swap? Lets go</a> 
          </Link>
          </h3>
      </main>
    </div>
  )
}